services:
    md_socom.api_manager:
        class: MD\SocomBundle\Service\ApiManager
        public: true
        arguments:
            - '%md_socom.api.url%'
            - '%md_socom.api.key%'

    md_socom.s3_client:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
        -
            version: latest
            region: '%env(AWS_SOCOM_REGION)%'
            credentials:
                key: '%env(AWS_SOCOM_KEY)%'
                secret: '%env(AWS_SOCOM_SECRET_KEY)%'

    md_socom.s3_manager:
        class: MD\SocomBundle\Service\S3Service
        public: true
        arguments:
        - '@md_socom.s3_client'
        - '%env(AWS_SOCOM_BUCKET_NAME)%'
